name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 */3 * * *"
      
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npx pnpm i --store=node_modules/.pnpm-store
      - name: Update gist
        run: npm run status
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: fccf32855105764135290761c8e815e6
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
